version: '2'

services:
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file: ./test.env

  web:
    build: image
    volumes:
      - '.:/code'
    ports:
    - 8080:80

volumes:
  db_data:
